# Generated by Django 4.2.4 on 2023-08-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.URLField(default='default_image_url'),
        ),
    ]
