# Generated by Django 4.2.4 on 2023-08-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoapp', '0003_alter_dish_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image_url',
            field=models.CharField(max_length=100000),
        ),
    ]
